name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/992989886232/locations/global/workloadIdentityPools/dbx-demand-forecast-wip/providers/dbx-demand-forecast-github'
          service_account: 'dbx-demand-forecast@dbx-demand-forecast.iam.gserviceaccount.com'

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            databricks_host:dbx-demand-forecast/dbx-demand-forecast-databricks-host
            databricks_token:dbx-demand-forecast/dbx-demand-forecast-databricks-token

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -e ".[local,test]"

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit

      - name: Workflow deployment (assets only upload)
        env:
          DATABRICKS_HOST: '${{ steps.secrets.outputs.databricks_host }}'
          DATABRICKS_TOKEN: '${{ steps.secrets.outputs.databricks_token }}'
        run: |
          dbx deploy dbx-demand-forecast-sample-etl --assets-only

      - name: Run the workflow in a jobless fashion
        env:
          DATABRICKS_HOST: '${{ steps.secrets.outputs.databricks_host }}'
          DATABRICKS_TOKEN: '${{ steps.secrets.outputs.databricks_token }}'
        run: |
          dbx launch dbx-demand-forecast-sample-etl --from-assets --trace
